name: Fetch dancers

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 8 1/8 * *'

jobs:
  fetchDancers:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/points/requirements.txt'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r points/requirements.txt
      
      # Runs a set of commands using the runners shell
      - name: Run fetch.py
        run: |
          cd points
          python fetch.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
