name: "Fetch all dancers(warning: slow and hits wsdc hard)"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    # m h DoM mon DoW
    - cron: '0 2 1 1/2 *'

jobs:
  fetchDancers:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: '**/points/requirements.txt'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r points/requirements.txt

      # Runs a set of commands using the runners shell
      - name: Run fetch.py
        env:
          OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
        run: |
          cd points
          FULLDANCERCHECK=1 python fetch.py

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
